version: '3.9'  # Compose file format

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage
    ports:
      - "5432:5432"  # Localhost:Container port
    networks:
      - app-network

  backend:
    build:
      context: ./appointly-api
      dockerfile: Appointly.API/Dockerfile
    container_name: backend-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./appointly-app
      dockerfile: Dockerfile
    container_name: appointly-app
    environment:
      - VITE_API_URL=http://backend-app:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
